[workspace]
members = [
  "junowen",
  "junowen-lib",
  "th19loader",
  "th19netdelayemulate",
  "th19netdelayemulate-hook",
  "th19padlight",
  "th19padlight-hook",
  "th19replayplayer",
  "th19replayplayer-hook",
  "th19replayrecorder",
  "th19savesettingsseparately",
  "th19seed",
]
default-members = ["junowen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Progre"]
license = "GPL-3.0"

[workspace.dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
