[workspace]
members = [
  "archives/th19netdelayemulate",
  "archives/th19padlight",
  "archives/th19seed",
  "junowen",
  "junowen-lib",
  "th19loader",
  "th19onlinevsfix",
  "th19replayplayer",
  "th19replayplayer-lib",
  "th19replayrecorder",
  "th19savesettingsseparately",
]
default-members = ["junowen"]
resolver = "2"

[workspace.package]
version = "0.2.0"
authors = ["Progre"]
license = "GPL-3.0"

[workspace.dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
junowen-lib = { path = "./junowen-lib" }
