[package]
name = "th19netdelayemulate-hook"
version.workspace = true
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
anyhow.workspace = true
bytes = "1.5.0"
junowen = { path = "../junowen" }
windows = { version = "0.51.1", features = [
] }
