[package]
name = "th19replayplayer"
version.workspace = true
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes = "1.5.0"
interprocess = "1.2.1"
junowen = { path = "../junowen" }
windows = "0.51.1"
