[package]
name = "th19onlinevsfix"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ['cdylib']
name = "th19_onlinevsfix"

[dependencies]
anyhow.workspace = true
junowen-lib.workspace = true
windows = "0.51.1"
