"Module loaded by th19.exe." = "Modulo ŝarĝita de th19.exe."
"Connected with guest." = "Konektita kun gasto."
"Guest disconnected." = "Gasto malkonektita."
"Connected with host." = "Konektita kun gastiganto."
"Host disconnected." = "Gastiganto malkonektita."
#
"1) Connect as Host" = "1) Konekti kiel Gastiganto"
"2) Connect as Guest" = "2) Konekti kiel Gasto"
"0) Exit" = "0) Eliri"
"Select (0-2): " = "Elektu (0-2):"
#
"junowen_hook.dll not found." = "junowen_hook.dll ne trovita."
"th19.exe process not found: " = "th19.exe procezo ne trovita: "
"waiting for th19.exe process..." = "atendas la procezon de th19.exe..."
"Failed to communicate with junowen_hook.dll: " = "Malsukcesis komuniki kun junowen_hook.dll: "
"th19 disconnected." = "th19 malkonektita."
#
"Your signaling code:" = "Via signalkodo:"
"It was copied to your clipboard. Share your signaling code with your guest." = "Ĝi estis kopiita al via tondujo. Kunhavigu vian signalkodon kun via gasto."
"Input guest's signaling code:" = "Enigu la signalkodon de gasto:"
"Waiting for guest to connect..." = "Atendante gaston por konekti..."
"Input host's signaling code:" = "Enigu la signalkodon de gastiganto:"
"It was copied to your clipboard. Share your signaling code with your host." = "Ĝi estis kopiita al via tondujo. Kunhavigu vian signalkodon kun via gastiganto."
"Waiting for host to connect..." = "Atendante la konekton de gastiganto..."
